name: Continuous Delivery
on:
  push:
    branches: [ main, github-action-cicd, java-11-update ]
  pull_request:
    branches: [ main, github-action-cicd, java-11-update ]

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build-maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'timurin'
    - name: Build with Maven
      working-directory: .
      run: mvn -B package 
  
  build-docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
      REGISTRY: ghcr.io
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.0
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.3.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Build Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        push: false
        file: packaging/docker/unix/eclipse-timurin-11-hotspot/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: "Deploy Docker Image: ${{ github.ref }}"
    needs:
      - build-maven
      - build-docker
    permissions:
      contents: read
      packages: write
    
    #TODO: There is slight double build overhead, but we prevent permissions from being exposed too widely
    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.0
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.3.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Build Docker image
      uses: docker/build-push-action@v2.6.1
      with:
        file: packaging/docker/unix/eclipse-timurin-11-hotspot/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
